language: python

python:
  - "3.6"

cache: pip

install:
  - pip install -U pip
  - pip install -U setuptools pipenv
  - pipenv sync --bare --dev

script:
  - rm -rf dist && python setup.py sdist && pip install dist/*.tar.gz
  - pytest -v
  - pylama
  - pylint --rcfile=pylintrc pyreleaser tests
