up:
  - python: 3.6.4
  - pipfile
  - python_develop

commands:
  lint:
    run: pylama; pylint --rcfile=pylintrc pyreleaser tests
  clean:
    run: find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
  test:
    run: pytest -v
